services:
  skeleton-app:
    depends_on:
      - firestore
    image: node:20.12.1-slim
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./skeleton-app:/app
      - skeleton-app-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"

  firestore:
    platform: linux/amd64
    build:
      context: .
      dockerfile: emulator.Dockerfile
    ports:
      - 8010:8000
    command:
      [
        "gcloud",
        "emulators",
        "firestore",
        "start",
        "--project",
        "local",
        "--host-port",
        "0.0.0.0:8000"
      ]

volumes:
  skeleton-app-node-modules:
